### ISSUE TITLE
ModuleNotFoundError: No module named 'utKit'

### ISSUE THREAD

**Issue by nonoumasy** [thespacedoctor/polyglot#7]
On Google colab, I tried installing using:
!pip install pypolyglot
!pip3 install pyicu
!pip3 install pycld2

it gives this error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-95deafc1d6ce> in <module>()
----> 1 from polyglot import ebook

/usr/local/lib/python3.6/dist-packages/polyglot/__init__.py in <module>()
----> 1 import utKit
      2 import cl_utils
      3 from printpdf import printpdf
      4 from htmlCleaner import htmlCleaner
      5 from ebook import ebook

ModuleNotFoundError: No module named 'utKit'

**Comment by krystofl** [comment]
Same issue in a local Python 3 virtualenv. I just did `pip install pypolyglot`, then

```
$ polyglot init
Traceback (most recent call last):
  File "/home/krystof/.virtualenvs/polyglot-tests/bin/polyglot", line 5, in <module>
    from polyglot.cl_utils import main
  File "/home/krystof/.virtualenvs/polyglot-tests/lib/python3.8/site-packages/polyglot/__init__.py", line 1, in <module>
    import utKit
ModuleNotFoundError: No module named 'utKit'
```

What is `utKit`, and how can one install it? There does note seem to be such a package on pypi

**Comment by ModnarUser** [comment]
Have the same issue with __Python 3__. When I modify the `__init__.py` in `polyglot/polyglot` from this
```python
import utKit
```
to this
```python
from . import utKit
```
my interpreter will find the file but runs into a bunch of __Python 2__ syntax related errors (`print "something" ` instead of `print("something")` etc.) So it seems like this project is not compatible with __Python 3__?
